1 - customtkinter
        interface com:
            NOME>  string e campo
            SETOR> string e campo
            OPERADOR> string e campo
            TÉCNICO> string e campo
            TEMPO DE USO ATÉ A PARADA> string e campo
            DATA> String e campo
            FAZER RELATÓRIO>  botão
            TIPO DE OCORRÊNCIA: MEC/ELE/AUT/PEÇA> lista


2 - banco
    Enviar as informações da GUI para o banco


3 - relatório
    Usar um botão do gui para gerar um GUI de relatório.

